name: CI
'on': push

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust and Cargo
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Install Dufs
        uses: taiki-e/cache-cargo-install-action@v1.3.0
        with:
          tool: dufs
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run container
        run: dufs -p 3000
  ngrok:
    runs-on: ubuntu-latest
    steps:
      - name: Ngrok Tunnel
        run: | 
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
            | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" \
            | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok
          ngrok config add-authtoken 1TLzdJdahXhagj12IjKlBDOnXJv_2KkrqgBtKYnMWAQBC7Mye
          ngrok http --domain=bluebird-noble-legally.ngrok-free.app 3000
