name: CI
'on': push

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust and Cargo
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Install Dufs
        run: |
          cargo install dufs          
  deploy:
    name: Deploys server to ngrok
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run container
        run: dufs -p 3000
      - name: Ngrok Tunnel
        uses: luisboto/ngrok-tunnel-action@v0.1.7.2
        with:
          timeout: 1h
          port: 3000
          ngrok_authtoken: '${{ secrets.NGROK_AUTHTOKEN }}'
          tunnel_type: http
